import { notFound, redirect } from "next/navigation";
import { Brand } from "@/components/brand";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { setIncidentMode } from "./actions";

export const dynamic = "force-dynamic";
export default async function AdminPage(){
  const client=await createClient();const {data:claims}=await client.auth.getClaims();const id=claims?.claims?.sub;if(!id)redirect("/login");
  const {data:profile}=await client.schema("app").from("profiles").select("is_superadmin").eq("id",id).single();if(!profile?.is_superadmin)notFound();
  const admin=createAdminClient();let system:null|Record<string,unknown>=null;let counts={models:0,runs:0,waitlist:0};
  if(admin){const [state,models,runs,waitlist]=await Promise.all([admin.schema("operations").from("system_state").select("*").eq("singleton",true).maybeSingle(),admin.schema("ai").from("models").select("*",{count:"exact",head:true}),admin.schema("ai").from("agent_runs").select("*",{count:"exact",head:true}),admin.schema("launch").from("waitlist_entries").select("*",{count:"exact",head:true})]);system=state.data;counts={models:models.count??0,runs:runs.count??0,waitlist:waitlist.count??0}}
  return <main className="content-page"><div className="shell" style={{paddingTop:28}}><Brand/></div><section className="shell content-hero"><div className="section-label">SUPERADMIN / CONTROL PLANE</div><h1>System control.</h1><p>Kill-switch and incident controls are deliberately separated from tenant product permissions.</p></section><section className="shell" style={{paddingBottom:100}}><div className="metric-grid"><div className="metric"><span>MODEL ALIASES</span><strong>{counts.models}</strong></div><div className="metric"><span>AGENT RUNS</span><strong>{counts.runs}</strong></div><div className="metric"><span>WAITLIST</span><strong>{counts.waitlist}</strong></div><div className="metric"><span>INCIDENT MODE</span><strong style={{fontSize:16}}>{String(system?.incident_mode??"unavailable")}</strong></div><div className="metric"><span>EXTERNAL TOOLS</span><strong style={{fontSize:16}}>{system?.external_tools_enabled?"enabled":"disabled"}</strong></div></div><article className="workspace-card" style={{marginTop:10}}><header><h2>Incident mode</h2><span>audited server action</span></header>{admin?<form className="workspace-form" action={setIncidentMode}><select name="mode" defaultValue={String(system?.incident_mode??"normal")} style={{background:"#090b0d",color:"white",border:"1px solid #2d333a",borderRadius:7,padding:"0 11px"}}><option value="normal">normal</option><option value="degraded">degraded</option><option value="maintenance">maintenance</option><option value="security_lockdown">security_lockdown</option></select><button className="button" type="submit">Apply mode</button></form>:<div className="empty-state"><div><b>Server control-plane secret is not configured.</b><p>Tenant UI remains usable; superadmin mutations stay unavailable until SUPABASE_SECRET_KEY exists in the server environment.</p></div></div>}</article></section></main>
}
