import { requireSuperadmin } from "@/lib/admin/guard";
import { createAudienceExport, createBroadcastDraft } from "../audience-actions";

export default async function AdminAudiencePage(){
 const {admin}=await requireSuperadmin();
 const [audience,exports,broadcasts,waitlist,users]=await Promise.all([
  admin.schema("marketing").from("audience_members").select("id,email,name,company,lifecycle_stage,marketing_consent,unsubscribed_at,source,created_at").order("created_at",{ascending:false}).limit(200),
  admin.schema("marketing").from("exports").select("id,export_type,status,row_count,storage_path,expires_at,error_code,created_at,completed_at").order("created_at",{ascending:false}).limit(50),
  admin.schema("marketing").from("broadcasts").select("id,provider,subject,status,audience_filter,scheduled_at,sent_count,failed_count,created_at").order("created_at",{ascending:false}).limit(50),
  admin.schema("launch").from("waitlist_entries").select("id",{count:"exact",head:true}),
  admin.schema("app").from("profiles").select("id",{count:"exact",head:true})
 ]);
 const marketingEligible=(audience.data??[]).filter(x=>x.marketing_consent&&!x.unsubscribed_at).length;
 return <div className="admin-page"><div className="admin-heading"><div className="admin-heading-copy"><div className="admin-eyebrow">VEXONYX / GROWTH</div><h1>Audience & email</h1><p>Export users safely or prepare consent-aware broadcasts. Transactional authentication/security email remains separate from marketing sends.</p></div></div>
 <section className="admin-metrics"><div className="admin-metric"><div className="admin-metric-label"><span>Waitlist</span><span>Source</span></div><strong>{waitlist.count??0}</strong></div><div className="admin-metric"><div className="admin-metric-label"><span>Users</span><span>Auth</span></div><strong>{users.count??0}</strong></div><div className="admin-metric"><div className="admin-metric-label"><span>Audience</span><span>Unified</span></div><strong>{audience.data?.length??0}</strong></div><div className="admin-metric"><div className="admin-metric-label"><span>Marketing eligible</span><span>Consent</span></div><strong>{marketingEligible}</strong></div></section>
 <section className="admin-grid equal"><article className="admin-card"><div className="admin-card-header"><h2>Export data</h2><span>Retryable CSV worker</span></div><form className="admin-card-body admin-form" action={createAudienceExport}><select className="admin-input" name="export_type" defaultValue="audience"><option value="audience">Unified audience</option><option value="waitlist">Waitlist</option><option value="users">Authenticated users</option><option value="customers">Customers</option></select><button className="admin-button primary" type="submit">Queue export</button><p>Exports are generated server-side through the leased worker queue, retry safely on transient failure and expire automatically. Secret fields, auth hashes and private project data are never included.</p></form></article>
 <article className="admin-card"><div className="admin-card-header"><h2>Broadcast draft</h2><span>Resend</span></div><form className="admin-card-body admin-form" action={createBroadcastDraft}><input className="admin-input" name="subject" placeholder="VEXONYX is live" required/><select className="admin-input" name="lifecycle_stage" defaultValue="waitlist"><option value="waitlist">Waitlist</option><option value="invited">Invited</option><option value="customer">Customers</option><option value="lead">Leads</option></select><button className="admin-button" type="submit">Create draft</button><p>Draft creation never sends email. Sending must enforce consent, unsubscribe suppression, provider rate limits and audit logging.</p></form></article></section>
 <section className="admin-card"><div className="admin-card-header"><h2>Unified audience</h2><span>Latest 200</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Person</th><th>Company</th><th>Stage</th><th>Marketing</th><th>Source</th><th>Added</th></tr></thead><tbody>{(audience.data??[]).map(a=><tr key={a.id}><td><b>{a.name||a.email}</b><small>{a.email}</small></td><td>{a.company||"—"}</td><td>{a.lifecycle_stage}</td><td>{a.unsubscribed_at?"unsubscribed":a.marketing_consent?"consented":"no consent"}</td><td>{a.source||"—"}</td><td>{new Date(a.created_at).toLocaleString("en-GB")}</td></tr>)}</tbody></table></div></section>
 <section className="admin-grid equal"><article className="admin-card"><div className="admin-card-header"><h2>Exports</h2><span>{exports.data?.length??0}</span></div>{(exports.data??[]).map(e=><div className="admin-health-row" key={e.id}><span>{e.export_type} · {new Date(e.created_at).toLocaleString("en-GB")}</span><b>{e.status}{e.row_count!=null?` · ${e.row_count} rows`:""}</b></div>)}</article><article className="admin-card"><div className="admin-card-header"><h2>Broadcasts</h2><span>{broadcasts.data?.length??0}</span></div>{(broadcasts.data??[]).map(b=><div className="admin-health-row" key={b.id}><span>{b.subject}</span><b>{b.status} · {b.sent_count}/{b.failed_count}</b></div>)}</article></section></div>
}
