import { notFound } from "next/navigation";
import { getWorkspace } from "@/lib/workspace";
import { FileUploader } from "@/components/file-uploader";
import { activateAuthorization, addFinding, addNote, addProjectMember, addScope, createAuthorization, createEngagement, createReport, duplicateProject, removeProjectMember, renameProject, setProjectArchive, softDeleteProject } from "./actions";

function roleLabel(role: string | null) { return String(role ?? "member").replace("organization_", "").replaceAll("_", " "); }
function percent(value: unknown) { const n = Number(value); return Number.isFinite(n) ? Math.round(n <= 1 ? n * 100 : n) : null; }

export default async function ProjectPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const ws = await getWorkspace();
  if (!ws?.organizationId) notFound();
  const { supabase, organizationId, role } = ws;
  const { data: project } = await supabase.schema("app").from("projects").select("id,name,description,status,updated_at").eq("id", id).eq("organization_id", organizationId).is("deleted_at", null).maybeSingle();
  if (!project) notFound();
  const isAdmin = role === "organization_owner" || role === "organization_admin";

  const [engagementsResult, scopeResult, authResult, findingsResult, evidenceResult, filesResult, notesResult, reportsResult, projectMembersResult, organizationMembersResult] = await Promise.all([
    supabase.schema("security").from("engagements").select("id,name,type,status,created_at").eq("project_id", id).eq("organization_id", organizationId).order("created_at", { ascending: false }),
    supabase.schema("security").from("engagement_scope").select("id,engagement_id,type,value,normalized_value,is_excluded").eq("project_id", id).eq("organization_id", organizationId).order("created_at", { ascending: false }),
    supabase.schema("security").from("authorization_records").select("id,engagement_id,status,valid_from,valid_until,notes").eq("project_id", id).eq("organization_id", organizationId).order("created_at", { ascending: false }),
    supabase.schema("security").from("findings").select("id,engagement_id,title,severity,confidence,status,summary,created_at").eq("project_id", id).eq("organization_id", organizationId).is("deleted_at", null).order("created_at", { ascending: false }),
    supabase.schema("security").from("finding_evidence").select("id,finding_id,evidence_type,current_version,created_at").eq("project_id", id).eq("organization_id", organizationId).order("created_at", { ascending: false }),
    supabase.schema("artifacts").from("files").select("id,original_name,size_bytes,status,classification,created_at").eq("project_id", id).eq("organization_id", organizationId).is("deleted_at", null).order("created_at", { ascending: false }),
    supabase.schema("app").from("project_notes").select("id,content,is_pinned,revision,created_at").eq("project_id", id).eq("organization_id", organizationId).is("deleted_at", null).order("created_at", { ascending: false }).limit(20),
    supabase.schema("reports").from("reports").select("id,title,status,updated_at").eq("project_id", id).eq("organization_id", organizationId).order("updated_at", { ascending: false }).limit(20),
    supabase.schema("app").from("project_members").select("user_id,role,created_at").eq("project_id", id).eq("organization_id", organizationId).order("created_at", { ascending: true }),
    supabase.schema("app").from("organization_members").select("user_id,role").eq("organization_id", organizationId),
  ]);

  const engagements = engagementsResult.data ?? [];
  const scopes = scopeResult.data ?? [];
  const authorizations = authResult.data ?? [];
  const findings = findingsResult.data ?? [];
  const evidence = evidenceResult.data ?? [];
  const files = filesResult.data ?? [];
  const notes = notesResult.data ?? [];
  const reports = reportsResult.data ?? [];
  const projectMembers = projectMembersResult.data ?? [];
  const organizationMembers = organizationMembersResult.data ?? [];
  const profileIds = Array.from(new Set([...projectMembers.map((m)=>m.user_id), ...organizationMembers.map((m)=>m.user_id)]));
  const { data: profiles } = profileIds.length ? await supabase.schema("app").from("profiles").select("id,display_name").in("id",profileIds) : { data: [] as Array<{id:string;display_name:string|null}> };
  const profileNames = new Map((profiles ?? []).map((p)=>[p.id,p.display_name]));
  const currentEngagement = engagements[0];
  const currentAuthorization = currentEngagement ? authorizations.find((a) => a.engagement_id === currentEngagement.id) : undefined;

  return <div className="app-content">
    <div className="app-heading"><div><div className="section-label">PROJECT / {project.status.toUpperCase()}</div><h1>{project.name}</h1><p>Authorization, scope, files, findings, evidence and reports stay connected to this project.</p></div><span>{roleLabel(role)}</span></div>
    <section className="metric-grid"><div className="metric"><span>ENGAGEMENTS</span><strong>{engagements.length}</strong></div><div className="metric"><span>SCOPE</span><strong>{scopes.length}</strong></div><div className="metric"><span>FINDINGS</span><strong>{findings.length}</strong></div><div className="metric"><span>EVIDENCE</span><strong>{evidence.length}</strong></div><div className="metric"><span>FILES</span><strong>{files.length}</strong></div><div className="metric"><span>REPORTS</span><strong>{reports.length}</strong></div></section>

    <section className="workspace-grid">
      <article className="workspace-card"><header><h2>Project</h2><span>{project.status}</span></header><form className="workspace-form" action={renameProject}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="organization_id" value={organizationId}/><input name="name" defaultValue={project.name} required maxLength={160}/><button className="button" type="submit">Rename</button></form><form className="workspace-form" action={setProjectArchive}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="organization_id" value={organizationId}/><input type="hidden" name="mode" value={project.status === "archived" ? "restore" : "archive"}/><button className="button secondary" type="submit">{project.status === "archived" ? "Restore project" : "Archive project"}</button></form><form className="workspace-form" action={duplicateProject}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="organization_id" value={organizationId}/><button className="button secondary" type="submit">Duplicate project shell</button></form>{isAdmin ? <form className="workspace-form" action={softDeleteProject}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="organization_id" value={organizationId}/><button className="button secondary" type="submit">Move to deleted projects</button></form> : null}</article>
      <article className="workspace-card"><header><h2>Authorization</h2><span>{currentAuthorization?.status ?? "not configured"}</span></header>{currentEngagement ? <><div className="project-row"><div><b>{currentEngagement.name}</b><small>{currentEngagement.type.replaceAll("_"," ")} · {currentEngagement.status}</small></div><span>{scopes.filter((s)=>s.engagement_id===currentEngagement.id).length} targets</span></div>{currentAuthorization ? <div className="project-row"><div><b>{currentAuthorization.status.replaceAll("_"," ")}</b><small>Valid until {currentAuthorization.valid_until ? new Date(currentAuthorization.valid_until).toLocaleString("en-GB") : "not set"}</small></div>{isAdmin && currentAuthorization.status !== "active" ? <form action={activateAuthorization}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="organization_id" value={organizationId}/><input type="hidden" name="engagement_id" value={currentEngagement.id}/><input type="hidden" name="authorization_id" value={currentAuthorization.id}/><button className="button button-small" type="submit">Activate</button></form> : <span>Verified</span>}</div> : <p className="form-note">No authorization record yet. Active external actions remain unavailable.</p>}</> : <div className="empty-state"><div><b>No engagement yet.</b><p>Define the assessment before any active security work.</p></div></div>}</article>
    </section>

    <section className="workspace-grid">
      <article className="workspace-card"><header><h2>Engagement</h2><span>Assessment details</span></header><form className="auth-form" action={createEngagement} style={{marginTop:16}}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="organization_id" value={organizationId}/><label>Name<input name="name" required maxLength={160} placeholder="Web application assessment"/></label><label>Type<select name="type" defaultValue="web_application"><option value="web_application">Web application</option><option value="api">API</option><option value="infrastructure">Infrastructure</option><option value="cloud">Cloud</option><option value="code_review">Code review</option><option value="general_security_assessment">General security assessment</option></select></label><button className="button" type="submit">Create engagement</button></form></article>
      <article className="workspace-card"><header><h2>Scope</h2><span>{isAdmin ? "Editable" : "Read only"}</span></header>{currentEngagement && isAdmin ? <form className="auth-form" action={addScope} style={{marginTop:16}}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="organization_id" value={organizationId}/><input type="hidden" name="engagement_id" value={currentEngagement.id}/><label>Target type<select name="type" defaultValue="domain"><option value="domain">Domain</option><option value="subdomain">Subdomain</option><option value="ip">IP</option><option value="cidr">CIDR</option><option value="application">Application</option><option value="repository">Repository</option><option value="cloud_resource">Cloud resource</option></select></label><label>Target<input name="value" required maxLength={2048} placeholder="example.com"/></label><label>Mode<select name="excluded" defaultValue="false"><option value="false">Included</option><option value="true">Excluded</option></select></label><button className="button" type="submit">Add scope</button></form> : null}{scopes.slice(0,8).map((scope)=><div className="project-row" key={scope.id}><div><b>{scope.normalized_value}</b><small>{scope.type.replaceAll("_"," ")}</small></div><span>{scope.is_excluded ? "EXCLUDED" : "IN SCOPE"}</span></div>)}</article>
    </section>

    <section className="workspace-grid">
      <article className="workspace-card"><header><h2>Authorization record</h2><span>Sensitive</span></header>{currentEngagement && isAdmin ? <form className="auth-form" action={createAuthorization} style={{marginTop:16}}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="organization_id" value={organizationId}/><input type="hidden" name="engagement_id" value={currentEngagement.id}/><label>Valid until<input type="datetime-local" name="valid_until" required/></label><label>Notes<input name="notes" maxLength={3000} placeholder="Authorization reference / conditions"/></label><button className="button" type="submit">Create review record</button></form> : <p className="form-note">Only organization owners and admins can define authorization.</p>}</article>
      <article className="workspace-card"><header><h2>Files</h2><span>100 MB max</span></header><FileUploader organizationId={organizationId} projectId={id}/>{files.slice(0,6).map((file)=><div className="project-row" key={file.id}><div><b>{file.original_name}</b><small>{Math.max(1,Math.round(Number(file.size_bytes)/1024))} KB · {String(file.classification).replaceAll("_"," ")}</small></div><span>{String(file.status).replaceAll("_"," ")}</span></div>)}</article>
    </section>

    <section className="workspace-grid">
      <article className="workspace-card"><header><h2>Findings</h2><span>Review and evidence</span></header><form className="auth-form" action={addFinding} style={{marginTop:16}}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="organization_id" value={organizationId}/><input type="hidden" name="engagement_id" value={currentEngagement?.id ?? ""}/><label>Title<input name="title" required maxLength={240} placeholder="Potential finding"/></label><label>Severity<select name="severity" defaultValue="medium"><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option><option value="informational">Informational</option></select></label><label>Summary<input name="summary" maxLength={4000}/></label><button className="button" type="submit">Add potential finding</button></form>{findings.slice(0,8).map((finding)=><div className="project-row" key={finding.id}><div><b>{finding.title}</b><small>{String(finding.severity).toUpperCase()} · {String(finding.status).replaceAll("_"," ")} · {evidence.filter((item)=>item.finding_id===finding.id).length} evidence</small></div><span>{finding.confidence == null ? "Review" : `${percent(finding.confidence)}%`}</span></div>)}</article>
      <article className="workspace-card"><header><h2>Notes</h2><span>Version history</span></header><form className="auth-form" action={addNote} style={{marginTop:16}}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="organization_id" value={organizationId}/><label>Project note<input name="content" required maxLength={20000} placeholder="Assessment note…"/></label><button className="button" type="submit">Add note</button></form>{notes.slice(0,6).map((note)=><div className="project-row" key={note.id}><div><b>{note.content.slice(0,100)}</b><small>revision {note.revision}</small></div><span>{note.is_pinned ? "PINNED" : ""}</span></div>)}</article>
    </section>

    <section className="workspace-grid">
      <article className="workspace-card"><header><h2>Reports</h2><span>{reports.length} reports</span></header><form className="workspace-form" action={createReport}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="organization_id" value={organizationId}/><input type="hidden" name="engagement_id" value={currentEngagement?.id ?? ""}/><input name="title" required maxLength={240} placeholder="Security assessment report"/><button className="button" type="submit">Create draft</button></form>{reports.length ? reports.map((report)=><div className="project-row" key={report.id}><div><b>{report.title}</b><small>Updated {new Date(report.updated_at).toLocaleString("en-GB")}</small></div><span>{String(report.status).replaceAll("_"," ")}</span></div>) : <div className="empty-state"><div><b>No reports yet.</b><p>Create a draft when findings are ready to organize into a report.</p></div></div>}</article>
      <article className="workspace-card"><header><h2>Project collaborators</h2><span>{projectMembers.length} assigned</span></header>{isAdmin && organizationMembers.length ? <form className="workspace-form" action={addProjectMember}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="organization_id" value={organizationId}/><select name="user_id" required defaultValue=""><option value="" disabled>Select organization member</option>{organizationMembers.map((member)=><option key={member.user_id} value={member.user_id}>{profileNames.get(member.user_id) || (member.user_id===ws.userId?"You":member.user_id.slice(0,8))}</option>)}</select><select name="role" defaultValue="member"><option value="member">Member</option><option value="viewer">Viewer</option></select><button className="button" type="submit">Assign</button></form> : null}{projectMembers.map((member)=><div className="project-row" key={member.user_id}><div><b>{profileNames.get(member.user_id) || (member.user_id===ws.userId?"You":"Team member")}</b><small>{String(member.role).replaceAll("_"," ")}</small></div>{isAdmin ? <form action={removeProjectMember}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="organization_id" value={organizationId}/><input type="hidden" name="user_id" value={member.user_id}/><button className="button button-small secondary" type="submit">Remove</button></form> : <span>{member.role}</span>}</div>)}</article>
    </section>
  </div>;
}
