import { requireSuperadmin } from "@/lib/admin/guard";
import { savePlan, savePlanEntitlement, savePlanPrice } from "../commerce-actions";

function money(minor: unknown,currency:unknown){return new Intl.NumberFormat("en",{style:"currency",currency:String(currency||"USD")}).format(Number(minor||0)/100)}
export default async function AdminBillingPage(){
 const {admin}=await requireSuperadmin();
 const [plans,prices,entitlements,subs,transactions]=await Promise.all([
  admin.schema("billing").from("plans").select("id,code,name,description,status,is_public,display_order,updated_at").order("display_order").order("name"),
  admin.schema("billing").from("plan_prices").select("id,plan_id,billing_interval,currency,unit_amount_minor,provider_price_id,active,effective_from").order("effective_from",{ascending:false}),
  admin.schema("billing").from("plan_entitlements").select("plan_id,entitlement_key,entitlement_value,updated_at").order("entitlement_key"),
  admin.schema("billing").from("subscriptions").select("id,organization_id,plan_id,status,current_period_end,cancel_at_period_end,provider_subscription_id,app_organizations:organization_id(name)").order("updated_at",{ascending:false}).limit(100),
  admin.schema("billing").from("payment_transactions").select("id,organization_id,kind,status,amount_minor,currency,credits,provider_transaction_id,created_at").order("created_at",{ascending:false}).limit(100)
 ]);
 const planRows=plans.data??[]; return <div className="admin-page"><div className="admin-heading"><div className="admin-heading-copy"><div className="admin-eyebrow">VEXONYX / COMMERCE</div><h1>Plans & billing</h1><p>One catalog drives customer checkout, entitlements, quotas and Superadmin reporting. Active prices require a provider-backed Stripe price ID.</p></div></div>
 <section className="admin-grid equal"><article className="admin-card"><div className="admin-card-header"><h2>Create plan</h2><span>Versionable catalog</span></div><form className="admin-card-body admin-form" action={savePlan}><input className="admin-input" name="code" placeholder="pro" required/><input className="admin-input" name="name" placeholder="VEXONYX Pro" required/><textarea className="admin-input" name="description" placeholder="Plan description"/><select className="admin-input" name="status" defaultValue="draft"><option>draft</option><option>active</option><option>retired</option></select><label><input type="checkbox" name="is_public" value="true"/> Public in customer billing</label><button className="admin-button primary" type="submit">Create plan</button></form></article>
 <article className="admin-card"><div className="admin-card-header"><h2>Add price</h2><span>Stripe-backed</span></div><form className="admin-card-body admin-form" action={savePlanPrice}><select className="admin-input" name="plan_id" required><option value="">Choose plan</option>{planRows.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className="admin-input" name="billing_interval" defaultValue="month"><option>month</option><option>year</option></select><input className="admin-input" name="currency" defaultValue="USD" maxLength={3}/><input className="admin-input" name="unit_amount_minor" type="number" min="0" placeholder="9900" required/><input className="admin-input" name="provider_price_id" placeholder="price_..."/><label><input type="checkbox" name="active" value="true"/> Active for checkout</label><button className="admin-button" type="submit">Add price</button></form></article></section>
 <section className="admin-grid equal"><article className="admin-card"><div className="admin-card-header"><h2>Entitlement</h2><span>JSON value</span></div><form className="admin-card-body admin-form" action={savePlanEntitlement}><select className="admin-input" name="plan_id" required><option value="">Choose plan</option>{planRows.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input className="admin-input" name="entitlement_key" placeholder="agent.max_runs_monthly" required/><input className="admin-input" name="entitlement_value" placeholder="100 or true or {&quot;soft&quot;:80,&quot;hard&quot;:100}" required/><button className="admin-button" type="submit">Save entitlement</button></form></article><article className="admin-card"><div className="admin-card-header"><h2>Catalog safety</h2><span>Fail closed</span></div><div className="admin-card-body admin-health"><div className="admin-health-row"><span>Client controls price</span><b>No</b></div><div className="admin-health-row"><span>Provider IDs editable</span><b>Superadmin only</b></div><div className="admin-health-row"><span>Webhook idempotency</span><b>Required</b></div><div className="admin-health-row"><span>GPU entitlement</span><b>Cannot enable runtime</b></div></div></article></section>
 <section className="admin-card"><div className="admin-card-header"><h2>Plan catalog</h2><span>{planRows.length}</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Plan</th><th>Status</th><th>Public</th><th>Prices</th><th>Entitlements</th></tr></thead><tbody>{planRows.map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.code}</small></td><td>{p.status}</td><td>{p.is_public?"yes":"no"}</td><td>{(prices.data??[]).filter(x=>x.plan_id===p.id).map(x=><small key={x.id}>{money(x.unit_amount_minor,x.currency)} / {x.billing_interval} · {x.active?"active":"inactive"}<br/></small>)}</td><td>{(entitlements.data??[]).filter(x=>x.plan_id===p.id).map(x=><small key={x.entitlement_key}>{x.entitlement_key}: {JSON.stringify(x.entitlement_value)}<br/></small>)}</td></tr>)}</tbody></table></div></section>
 <section className="admin-card"><div className="admin-card-header"><h2>Subscriptions</h2><span>{subs.data?.length??0}</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Organization</th><th>Plan</th><th>Status</th><th>Period end</th><th>Provider</th></tr></thead><tbody>{(subs.data??[]).map(s=><tr key={s.id}><td>{s.organization_id}</td><td>{planRows.find(p=>p.id===s.plan_id)?.name||"—"}</td><td>{s.status}</td><td>{s.current_period_end?new Date(s.current_period_end).toLocaleString("en-GB"):"—"}</td><td><small>{s.provider_subscription_id||"—"}</small></td></tr>)}</tbody></table></div></section>
 <section className="admin-card"><div className="admin-card-header"><h2>Recent transactions</h2><span>{transactions.data?.length??0}</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Organization</th><th>Type</th><th>Status</th><th>Amount</th><th>Credits</th><th>Time</th></tr></thead><tbody>{(transactions.data??[]).map(t=><tr key={t.id}><td>{t.organization_id}</td><td>{t.kind}</td><td>{t.status}</td><td>{money(t.amount_minor,t.currency)}</td><td>{Number(t.credits).toLocaleString()}</td><td>{new Date(t.created_at).toLocaleString("en-GB")}</td></tr>)}</tbody></table></div></section></div>
}
