import { requireSuperadmin } from "@/lib/admin/guard";
import { savePlan, savePlanEntitlement, savePlanPrice } from "../commerce-actions";

function money(minor: unknown,currency:unknown){return new Intl.NumberFormat("en",{style:"currency",currency:String(currency||"USD")}).format(Number(minor||0)/100)}
export default async function AdminBillingPage(){
 const {admin}=await requireSuperadmin();
 const [plans,prices,entitlements,subs,transactions]=await Promise.all([
  admin.schema("billing").from("plans").select("id,code,name,description,status,is_public,display_order,metadata,updated_at").order("display_order").order("name"),
  admin.schema("billing").from("plan_prices").select("id,plan_id,billing_interval,currency,unit_amount_minor,provider_price_id,active,effective_from,effective_to").order("effective_from",{ascending:false}),
  admin.schema("billing").from("plan_entitlements").select("plan_id,entitlement_key,entitlement_value,updated_at").order("entitlement_key"),
  admin.schema("billing").from("subscriptions").select("id,organization_id,plan_id,status,current_period_end,cancel_at_period_end,provider_subscription_id,app_organizations:organization_id(name)").order("updated_at",{ascending:false}).limit(100),
  admin.schema("billing").from("payment_transactions").select("id,organization_id,kind,status,amount_minor,currency,credits,provider_transaction_id,created_at").order("created_at",{ascending:false}).limit(100)
 ]);
 const planRows=plans.data??[]; return <div className="admin-page"><div className="admin-heading"><div className="admin-heading-copy"><div className="admin-eyebrow">VEXONYX / COMMERCE</div><h1>Plans & billing</h1><p>Plans, checkout prices and usage rights are managed here. Publishing an active price creates the Stripe product/price automatically and atomically replaces the previous active version for that interval and currency.</p></div></div>
 <section className="admin-grid equal"><article className="admin-card"><div className="admin-card-header"><h2>Create plan</h2><span>Customer catalog</span></div><form className="admin-card-body admin-form" action={savePlan}><input className="admin-input" name="code" placeholder="pro" required/><input className="admin-input" name="name" placeholder="VEXONYX Pro" required/><textarea className="admin-input" name="description" placeholder="What this plan is for"/><select className="admin-input" name="status" defaultValue="draft"><option>draft</option><option>active</option><option>retired</option></select><label><input type="checkbox" name="is_public" value="true"/> Show this plan to customers</label><button className="admin-button primary" type="submit">Create plan</button></form></article>
 <article className="admin-card"><div className="admin-card-header"><h2>Publish price</h2><span>Stripe synced</span></div><form className="admin-card-body admin-form" action={savePlanPrice}><select className="admin-input" name="plan_id" required><option value="">Choose plan</option>{planRows.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className="admin-input" name="billing_interval" defaultValue="month"><option value="month">Monthly</option><option value="year">Yearly</option></select><input className="admin-input" name="currency" defaultValue="USD" maxLength={3} aria-label="Currency"/><input className="admin-input" name="unit_amount_minor" type="number" min="0" placeholder="9900 = $99.00" required/><label><input type="checkbox" name="active" value="true" defaultChecked/> Publish for customer checkout now</label><button className="admin-button primary" type="submit">Publish price</button><small>VEXONYX creates and stores the Stripe IDs. A previous active price for the same plan, interval and currency is retired in the same database transaction.</small></form></article></section>
 <section className="admin-grid equal"><article className="admin-card"><div className="admin-card-header"><h2>Plan allowance</h2><span>Entitlement</span></div><form className="admin-card-body admin-form" action={savePlanEntitlement}><select className="admin-input" name="plan_id" required><option value="">Choose plan</option>{planRows.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input className="admin-input" name="entitlement_key" list="entitlement-keys" placeholder="agent.max_runs_monthly" required/><datalist id="entitlement-keys"><option value="agent.max_runs_monthly"/><option value="generation.max_monthly"/><option value="sandbox.max_minutes_monthly"/><option value="connectors.max_active"/><option value="projects.max_active"/><option value="team.max_members"/><option value="credits.monthly_included"/><option value="model.tier"/></datalist><input className="admin-input" name="entitlement_value" placeholder="100, true, &quot;pro&quot; or {&quot;hard&quot;:100}" required/><button className="admin-button" type="submit">Save allowance</button><small>Values are version-independent JSON so plan limits can cover model access, agents, sandboxes, connectors, teams and monthly included credits.</small></form></article><article className="admin-card"><div className="admin-card-header"><h2>Catalog safety</h2><span>Fail closed</span></div><div className="admin-card-body admin-health"><div className="admin-health-row"><span>Client controls price</span><b>No</b></div><div className="admin-health-row"><span>Stripe IDs copied manually</span><b>No</b></div><div className="admin-health-row"><span>One active price/version</span><b>Enforced</b></div><div className="admin-health-row"><span>Webhook idempotency</span><b>Required</b></div><div className="admin-health-row"><span>GPU entitlement</span><b>Cannot enable runtime</b></div></div></article></section>
 <section className="admin-card"><div className="admin-card-header"><h2>Plan catalog</h2><span>{planRows.length}</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Plan</th><th>Status</th><th>Public</th><th>Prices</th><th>Allowances</th></tr></thead><tbody>{planRows.map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.code}</small></td><td>{p.status}</td><td>{p.is_public?"yes":"no"}</td><td>{(prices.data??[]).filter(x=>x.plan_id===p.id).map(x=><small key={x.id}>{money(x.unit_amount_minor,x.currency)} / {x.billing_interval} · {x.active?"active":"retired"}<br/>{x.provider_price_id||"draft"}<br/></small>)}</td><td>{(entitlements.data??[]).filter(x=>x.plan_id===p.id).map(x=><small key={x.entitlement_key}>{x.entitlement_key}: {JSON.stringify(x.entitlement_value)}<br/></small>)}</td></tr>)}</tbody></table></div></section>
 <section className="admin-card"><div className="admin-card-header"><h2>Subscriptions</h2><span>{subs.data?.length??0}</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Organization</th><th>Plan</th><th>Status</th><th>Period end</th><th>Provider</th></tr></thead><tbody>{(subs.data??[]).map(s=><tr key={s.id}><td>{s.organization_id}</td><td>{planRows.find(p=>p.id===s.plan_id)?.name||"—"}</td><td>{s.status}</td><td>{s.current_period_end?new Date(s.current_period_end).toLocaleString("en-GB"):"—"}</td><td><small>{s.provider_subscription_id||"—"}</small></td></tr>)}</tbody></table></div></section>
 <section className="admin-card"><div className="admin-card-header"><h2>Recent transactions</h2><span>{transactions.data?.length??0}</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Organization</th><th>Type</th><th>Status</th><th>Amount</th><th>Credits</th><th>Time</th></tr></thead><tbody>{(transactions.data??[]).map(t=><tr key={t.id}><td>{t.organization_id}</td><td>{t.kind}</td><td>{t.status}</td><td>{money(t.amount_minor,t.currency)}</td><td>{Number(t.credits).toLocaleString()}</td><td>{new Date(t.created_at).toLocaleString("en-GB")}</td></tr>)}</tbody></table></div></section></div>
}