import { ContentPage } from "@/components/content-page";

export default function Page() {
  return <ContentPage
    label="LEGAL · EFFECTIVE AUGUST 15, 2026"
    title="Privacy notice"
    intro="VEXONYX is operated by Diversa Solutions LLC, Wyoming, United States. This notice explains how we handle personal information across the website, accounts, billing and the VEXONYX security platform. For customer-provided project data, our role depends on the processing described below."
    cards={[
      { title: "Who is responsible", body: "Diversa Solutions LLC is the controller for VEXONYX account, website, billing, support, security and business-administration data. When an organization submits personal data inside a security engagement and determines why that data is processed, the organization is generally the controller and Diversa Solutions LLC acts as its processor under the VEXONYX Data Processing Addendum." },
      { title: "Information we collect", body: "We may process identity and contact information; account and organization details; billing, transaction and tax information; authentication and security data; IP-derived request and device information; usage and audit events; support communications; waitlist information; and customer-provided project files, findings, evidence, logs, code, network or application data and other content needed to provide the service." },
      { title: "Customer security content", body: "Security engagement content can be highly sensitive. We process it to provide the requested workspace, analysis, evidence, reporting, storage and security functions, to protect the platform, and as otherwise instructed by the customer or required by law. Customer security content is not sold for advertising and is not used by default to train shared public models." },
      { title: "Why we process data", body: "We process information to provide and administer the service and contracts; authenticate users; process payments and taxes; allocate usage and credits; provide support; prevent fraud, abuse and unauthorized security activity; maintain auditability; secure and improve reliability; communicate service or legal changes; comply with law; establish or defend legal claims; and, where consent is required, for any optional processing to which you consent." },
      { title: "Legal bases where GDPR or UK GDPR applies", body: "Depending on the activity, processing is based on performance of a contract or steps requested before a contract, compliance with legal obligations, our legitimate interests in operating and securing the service and preventing abuse, or consent where consent is the appropriate legal basis. You may withdraw consent at any time for processing that depends on consent, without affecting prior lawful processing." },
      { title: "Sources", body: "We receive information directly from users and customer administrators, from systems and files submitted to the service, from service providers involved in authentication, hosting, payments and communications, and from technical interactions with VEXONYX. Customers are responsible for ensuring they have authority and a lawful basis to submit third-party personal data to security projects." },
      { title: "Service providers and subprocessors", body: "We use vendors that help operate VEXONYX, including cloud hosting, database/authentication/storage, payment and billing, and transactional email providers. They process information only for the relevant service purposes under their applicable contracts. Our current material subprocessors are listed on the Subprocessors page." },
      { title: "No sale or behavioral advertising", body: "We do not sell personal information. We do not share personal information for cross-context behavioral advertising, and the current VEXONYX product does not use advertising cookies or an advertising analytics stack. If that changes, we will update this notice and deploy any consent or opt-out controls required before such processing begins." },
      { title: "International transfers", body: "Diversa Solutions LLC is established in the United States and providers may process data in the United States or other countries. Where data-protection law requires a transfer mechanism, we use or make available an appropriate mechanism and contractual safeguards, which may include applicable standard contractual clauses or another legally recognized transfer basis." },
      { title: "Retention", body: "We retain data only for as long as reasonably necessary for the purpose collected and applicable legal, security and dispute requirements. Account and customer-content retention follows the service configuration and contract; backups age out through ordinary backup lifecycles. Billing, transaction, contract and legal-acceptance records may be retained for up to seven years or longer if required by law or a legal claim. Security and abuse records may be retained as reasonably necessary to protect VEXONYX and its users." },
      { title: "Security", body: "We use technical and organizational safeguards designed for a multi-tenant security platform, including access controls, tenant isolation, least-privilege service boundaries, audit logging and security monitoring. No online system can be guaranteed perfectly secure, and customers must protect credentials, limit submitted data to what is necessary and follow their own engagement and confidentiality obligations." },
      { title: "Your privacy rights", body: "Depending on your location and the applicable law, you may have rights to information, access, correction, deletion, restriction, objection, portability, withdrawal of consent and to complain to a supervisory authority. Rights can be limited where an exemption applies, including legal obligations, security, fraud prevention or the establishment, exercise or defense of legal claims." },
      { title: "United States state rights", body: "Where an applicable U.S. state privacy law grants rights, eligible individuals may request access, correction or deletion and may exercise any other rights available under that law. VEXONYX does not discriminate against users for exercising applicable privacy rights. Because we do not sell personal information or use it for cross-context behavioral advertising, there is currently no sale/share opt-out workflow to operate." },
      { title: "Automated processing and AI", body: "VEXONYX may use automated systems and AI to analyze technical material and produce security assistance. These systems are product functionality, not a substitute for qualified human review. We do not intend to make solely automated decisions about individuals that produce legal or similarly significant effects unless the required legal basis, notices and safeguards are in place." },
      { title: "Cookies and similar technologies", body: "Strictly necessary authentication, session, security and preference technologies may be used to provide requested functionality. The current production site does not intentionally deploy non-essential advertising or marketing cookies. See the Cookies page for the current implementation and the rules we follow before enabling optional categories." },
      { title: "Children", body: "VEXONYX is a professional cybersecurity service and is not directed to children. You must be at least 18 years old to create or control a paid VEXONYX account unless applicable law and an authorized organization expressly permit otherwise." },
      { title: "Contact and complaints", body: "Privacy requests can be sent to info@vexonyx.com. Operator: Diversa Solutions LLC, 30 N Gould St, Sheridan, Wyoming 82801, United States. If GDPR or UK GDPR applies, you may also lodge a complaint with the competent data-protection authority in your place of residence, work or the location of the alleged infringement." },
      { title: "Changes to this notice", body: "We may update this notice as VEXONYX evolves. Material changes will be communicated by a reasonable method before or when they take effect where required. The effective date shown above identifies the current version." },
    ]}
  />;
}
