import { ContentPage } from "@/components/content-page";

export default function Page() {
  return <ContentPage
    label="LEGAL · EFFECTIVE AUGUST 15, 2026"
    title="Refund & cancellation policy"
    intro="VEXONYX uses a no-refund model for paid subscriptions and credit packs, subject to mandatory legal rights, verified billing errors and the specific exceptions below. This policy also explains how recurring subscriptions are cancelled."
    cards={[
      { title: "No-refund rule", body: "Except where applicable law requires a refund or this policy expressly says otherwise, payments to VEXONYX are final and non-refundable. This includes subscription fees for a billing period that has already started and one-time purchases of usage credits." },
      { title: "Monthly subscriptions", body: "Subscriptions renew automatically at the interval shown at checkout until cancelled. You can stop future renewal online from VEXONYX billing controls. Unless mandatory law requires otherwise, cancellation takes effect at the end of the current paid billing period and does not produce a prorated refund for unused days in that period." },
      { title: "Credit packs", body: "One-time credit-pack purchases are final and non-refundable after successful payment and credit allocation, except for duplicate charges, verified billing errors, an unauthorized transaction for which a refund is legally required, or another mandatory legal right. Unused credits do not create a cash-refund entitlement and have no cash redemption value." },
      { title: "Credit expiration", body: "Any credit-expiration rule displayed for a specific product or order controls. If no expiration is stated at purchase, this policy does not create a separate expiration date merely because a subscription is later cancelled." },
      { title: "Duplicate or incorrect charges", body: "If VEXONYX or its payment provider charges the same purchase more than once or processes an amount different from the amount you authorized, contact info@vexonyx.com promptly. After verification, we will correct the billing record and issue any refund required to reverse the error." },
      { title: "Unauthorized payments", body: "If you believe a payment was unauthorized, contact us and your payment provider promptly. We may ask for information reasonably needed to investigate and secure the account. Nothing in this policy limits rights you have under payment-card rules or applicable law." },
      { title: "Failed or unavailable service", body: "Temporary downtime, maintenance, model unavailability, provider incidents, unused capacity or dissatisfaction with AI output does not automatically create a cash-refund right. Where appropriate, VEXONYX may provide service credits or restore incorrectly consumed credits. Mandatory rights for a service that was not supplied remain unaffected." },
      { title: "Billing reversals and credits", body: "If a payment is refunded, reversed, charged back or determined to be fraudulent, VEXONYX may reverse credits or plan benefits granted for that payment so the account does not retain unpaid service value. We will not use this provision to remove credits that were separately paid for and remain valid." },
      { title: "Taxes", body: "When a refund is legally due, any tax collected on the refunded amount will be handled according to applicable tax rules and payment-provider capabilities. Taxes that VEXONYX was required to remit may not be independently refundable where the law provides otherwise." },
      { title: "Consumer withdrawal rights", body: "VEXONYX is designed for professional and business cybersecurity use. If you nevertheless qualify as a consumer and mandatory law gives you a cooling-off or withdrawal right, this policy does not waive that right. Any request for immediate service performance or acknowledgement affecting a statutory withdrawal right is effective only to the extent permitted by the law that applies." },
      { title: "European consumer rights", body: "Where EU or EEA consumer law applies, online services can carry statutory withdrawal rights and specific rules for services or digital content started during the withdrawal period. VEXONYX will honor any non-waivable right and will obtain any express request, consent or acknowledgement required before relying on an exception." },
      { title: "How to cancel", body: "Use the cancellation control in VEXONYX under Plan & credits to stop automatic renewal. The service must not require a sales call or retention conversation to complete online cancellation. If the online control is unavailable, contact info@vexonyx.com and we will provide a reasonable alternative cancellation method." },
      { title: "When cancellation is effective", body: "A scheduled cancellation stops the next recurring renewal. You may continue using paid plan benefits through the current period unless the account is suspended or terminated for security, abuse, legal or non-payment reasons. A cancellation confirmation or updated billing status is evidence that future renewal has been stopped." },
      { title: "Chargebacks", body: "A chargeback should not be used to obtain both service value and a payment reversal. We may suspend billing-related access while a dispute is investigated and may provide transaction, consent and service records to the payment provider. This does not limit a lawful right to dispute an unauthorized or incorrect charge." },
      { title: "Contact", body: "Refund, billing-error and cancellation questions can be sent to info@vexonyx.com. Operator: Diversa Solutions LLC, 30 N Gould St, Sheridan, Wyoming 82801, United States." },
    ]}
  />;
}
