import Link from "next/link";
import { notFound } from "next/navigation";
import { getWorkspace } from "@/lib/workspace";
import { deleteReportSection, requestReportExport, saveReportSection, snapshotReport, updateReport } from "./actions";

const sectionDefinitions=[
  ["cover","Cover"],["executive_summary","Executive Summary"],["scope","Scope"],["methodology","Methodology"],["overall_risk","Overall Risk"],["findings","Findings"],["evidence","Evidence"],["recommendations","Recommendations"],["limitations","Limitations"],["appendix","Appendix"],
] as const;
function sectionText(content:unknown){if(!content||typeof content!=="object"||Array.isArray(content))return "";const text=(content as Record<string,unknown>).text;return typeof text==="string"?text:"";}

export default async function ReportPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const ws=await getWorkspace();if(!ws?.organizationId)notFound();
  const {data:report}=await ws.supabase.schema("reports").from("reports").select("id,project_id,engagement_id,title,status,created_at,updated_at").eq("id",id).eq("organization_id",ws.organizationId).maybeSingle();
  if(!report)notFound();
  const [{data:project},{data:sections},{data:versions},{data:exports}]=await Promise.all([
    ws.supabase.schema("app").from("projects").select("id,name").eq("id",report.project_id).eq("organization_id",ws.organizationId).maybeSingle(),
    ws.supabase.schema("reports").from("report_sections").select("id,section_key,title,position,content,updated_at").eq("report_id",id).eq("organization_id",ws.organizationId).order("position",{ascending:true}),
    ws.supabase.schema("reports").from("report_versions").select("id,version,content_hash,created_at").eq("report_id",id).eq("organization_id",ws.organizationId).order("version",{ascending:false}).limit(20),
    ws.supabase.schema("reports").from("report_exports").select("id,report_version_id,format,status,error,created_at,completed_at").eq("report_id",id).eq("organization_id",ws.organizationId).order("created_at",{ascending:false}).limit(30),
  ]);
  const byKey=new Map((sections??[]).map((section)=>[section.section_key,section]));const latestVersion=versions?.[0];
  return <div className="app-content">
    <div className="app-heading"><div><div className="section-label">REPORT / {report.status.toUpperCase()}</div><h1>{report.title}</h1><p>{project?.name??"Project"} · sections, immutable snapshots and export jobs stay connected.</p></div><Link className="button button-small secondary" href={`/app/projects/${report.project_id}`}>Project →</Link></div>
    <section className="metric-grid"><div className="metric"><span>SECTIONS</span><strong>{sections?.length??0}</strong></div><div className="metric"><span>VERSIONS</span><strong>{versions?.length??0}</strong></div><div className="metric"><span>EXPORTS</span><strong>{exports?.length??0}</strong></div></section>
    <section className="workspace-grid">
      <article className="workspace-card"><header><h2>Report</h2><span>{report.status}</span></header><form className="auth-form" action={updateReport} style={{marginTop:16}}><input type="hidden" name="report_id" value={id}/><input type="hidden" name="organization_id" value={ws.organizationId}/><label>Title<input name="title" required maxLength={240} defaultValue={report.title}/></label><label>Status<select name="status" defaultValue={report.status}><option value="draft">Draft</option><option value="ready">Ready</option><option value="archived">Archived</option></select></label><button className="button" type="submit">Save report</button></form></article>
      <article className="workspace-card"><header><h2>Version snapshot</h2><span>{latestVersion?`v${latestVersion.version}`:"No snapshot"}</span></header><div className="empty-state"><div><b>Freeze the current report before export.</b><p>A snapshot captures the report and ordered sections with a SHA-256 content hash. Later edits create a new version instead of changing the old one.</p></div></div><form className="workspace-form" action={snapshotReport}><input type="hidden" name="report_id" value={id}/><input type="hidden" name="organization_id" value={ws.organizationId}/><button className="button" type="submit">Create snapshot</button></form>{latestVersion?<div className="project-row"><div><b>Version {latestVersion.version}</b><small>SHA-256 {latestVersion.content_hash.slice(0,20)}… · {new Date(latestVersion.created_at).toLocaleString("en-GB")}</small></div><span>Immutable</span></div>:null}</article>
    </section>
    <section className="workspace-card"><header><h2>Report sections</h2><span>Standard structure</span></header>{sectionDefinitions.map(([key,label])=>{const section=byKey.get(key);return <div key={key} style={{borderTop:"1px solid #20262c",padding:"18px 0"}}><form className="auth-form" action={saveReportSection}><input type="hidden" name="report_id" value={id}/><input type="hidden" name="organization_id" value={ws.organizationId}/><input type="hidden" name="section_key" value={key}/><label>Section<input name="title" required maxLength={240} defaultValue={section?.title??label}/></label><label>Content<textarea name="content" maxLength={30000} defaultValue={sectionText(section?.content)} placeholder={`Write ${label.toLowerCase()}…`}/></label><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="button button-small" type="submit">{section?"Save section":"Add section"}</button></div></form>{section?<form className="workspace-form" action={deleteReportSection}><input type="hidden" name="report_id" value={id}/><input type="hidden" name="organization_id" value={ws.organizationId}/><input type="hidden" name="section_id" value={section.id}/><button className="button button-small secondary" type="submit">Remove section</button></form>:null}</div>})}</section>
    <section className="workspace-grid">
      <article className="workspace-card"><header><h2>Export</h2><span>{latestVersion?`Version ${latestVersion.version}`:"Snapshot required"}</span></header>{latestVersion?<form className="auth-form" action={requestReportExport} style={{marginTop:16}}><input type="hidden" name="report_id" value={id}/><input type="hidden" name="organization_id" value={ws.organizationId}/><input type="hidden" name="report_version_id" value={latestVersion.id}/><label>Format<select name="format" defaultValue="pdf"><option value="pdf">PDF</option><option value="docx">DOCX</option><option value="markdown">Markdown</option><option value="json">JSON</option></select></label><button className="button" type="submit">Queue export</button></form>:<div className="empty-state"><div><b>Create a snapshot first.</b><p>Exports always target an immutable report version.</p></div></div>}</article>
      <article className="workspace-card"><header><h2>Export jobs</h2><span>{exports?.length??0}</span></header>{exports?.length?exports.map((item)=><div className="project-row" key={item.id}><div><b>{item.format.toUpperCase()}</b><small>{new Date(item.created_at).toLocaleString("en-GB")}{item.error?` · ${item.error}`:""}</small></div><span>{item.status}</span></div>):<div className="empty-state"><div><b>No exports requested.</b><p>Export jobs remain queued until the report renderer is connected.</p></div></div>}</article>
    </section>
  </div>;
}
