import Link from "next/link";
import { notFound } from "next/navigation";
import { requireSuperadmin } from "@/lib/admin/guard";
import { resetUserProductHistory } from "../../commerce-actions";
import { setUserSuspension } from "../../actions";

function dt(v:unknown){return v?new Date(String(v)).toLocaleString("en-GB"):"—"}
export default async function AdminUserDetailPage({params}:{params:Promise<{userId:string}>}){
 const {userId:target}=await params; const {admin,userId:self}=await requireSuperadmin();
 const auth=await admin.auth.admin.getUserById(target); if(auth.error||!auth.data.user)notFound(); const u=auth.data.user;
 const [profile,memberships,conversations,runs,requests,usage,transactions]=await Promise.all([
  admin.schema("app").from("profiles").select("id,display_name,timezone,is_superadmin,created_at,updated_at").eq("id",target).maybeSingle(),
  admin.schema("app").from("organization_members").select("organization_id,role,app_organizations:organization_id(name,status)").eq("user_id",target),
  admin.schema("app").from("conversations").select("id,organization_id,title,status,created_at,updated_at").eq("user_id",target).order("updated_at",{ascending:false}).limit(50),
  admin.schema("ai").from("agent_runs").select("id,organization_id,state,objective,total_tokens,total_tool_calls,total_cost,created_at,completed_at").eq("user_id",target).order("created_at",{ascending:false}).limit(50),
  admin.schema("ai").from("generation_requests").select("id,organization_id,status,task_type,input_tokens,output_tokens,cost,created_at").eq("user_id",target).order("created_at",{ascending:false}).limit(100),
  admin.schema("usage").from("usage_events").select("id,organization_id,event_type,quantity,unit,cost,created_at").eq("user_id",target).order("created_at",{ascending:false}).limit(100),
  admin.schema("billing").from("payment_transactions").select("id,organization_id,kind,status,amount_minor,currency,credits,created_at").eq("user_id",target).order("created_at",{ascending:false}).limit(100)
 ]);
 const orgIds=(memberships.data??[]).map(m=>m.organization_id); const [subs,credits]=await Promise.all([
  orgIds.length?admin.schema("billing").from("subscriptions").select("organization_id,plan_id,status,current_period_end,cancel_at_period_end,provider_subscription_id").in("organization_id",orgIds):Promise.resolve({data:[]}),
  orgIds.length?admin.schema("billing").from("credit_accounts").select("organization_id,balance,lifetime_purchased,lifetime_granted,lifetime_consumed").in("organization_id",orgIds):Promise.resolve({data:[]})
 ]);
 const suspended=Boolean(u.banned_until&&new Date(u.banned_until)>new Date()); const protectedUser=Boolean(profile.data?.is_superadmin)||target===self;
 return <div className="admin-page"><div className="admin-heading"><div className="admin-heading-copy"><div className="admin-eyebrow">VEXONYX / USER</div><h1>{profile.data?.display_name||u.email||target}</h1><p>{u.email} · {target}</p></div><div className="admin-heading-actions"><Link className="admin-button" href="/admin/users">← Users</Link></div></div>
 <section className="admin-metrics"><div className="admin-metric"><div className="admin-metric-label"><span>Access</span></div><strong style={{fontSize:20}}>{profile.data?.is_superadmin?"Superadmin":suspended?"Suspended":"Active"}</strong></div><div className="admin-metric"><div className="admin-metric-label"><span>Organizations</span></div><strong>{orgIds.length}</strong></div><div className="admin-metric"><div className="admin-metric-label"><span>Conversations</span></div><strong>{conversations.data?.length??0}</strong></div><div className="admin-metric"><div className="admin-metric-label"><span>Agent runs</span></div><strong>{runs.data?.length??0}</strong></div><div className="admin-metric"><div className="admin-metric-label"><span>AI requests</span></div><strong>{requests.data?.length??0}</strong></div><div className="admin-metric"><div className="admin-metric-label"><span>Purchases</span></div><strong>{transactions.data?.length??0}</strong></div></section>
 <section className="admin-grid equal"><article className="admin-card"><div className="admin-card-header"><h2>Account</h2><span>{dt(u.last_sign_in_at)}</span></div><div className="admin-card-body admin-health"><div className="admin-health-row"><span>Created</span><b>{dt(u.created_at)}</b></div><div className="admin-health-row"><span>Last sign-in</span><b>{dt(u.last_sign_in_at)}</b></div><div className="admin-health-row"><span>Email confirmed</span><b>{dt(u.email_confirmed_at)}</b></div><div className="admin-health-row"><span>Timezone</span><b>{profile.data?.timezone||"UTC"}</b></div></div>{!protectedUser?<form className="admin-card-body" action={setUserSuspension}><input type="hidden" name="user_id" value={target}/><input type="hidden" name="suspended" value={suspended?"false":"true"}/><button className={`admin-button ${suspended?"":"danger"}`} type="submit">{suspended?"Restore account":"Suspend account"}</button></form>:null}</article>
 <article className="admin-card"><div className="admin-card-header"><h2>Reset product history</h2><span>Destructive</span></div><form className="admin-card-body admin-form" action={resetUserProductHistory}><input type="hidden" name="user_id" value={target}/><p>Deletes this user's conversations/messages and AI memory. Billing, usage, audit logs, security findings and organization records are preserved.</p><input className="admin-input" name="confirmation" placeholder="Type RESET HISTORY" required disabled={protectedUser}/><button className="admin-button danger" type="submit" disabled={protectedUser}>Reset history</button></form></article></section>
 <section className="admin-card"><div className="admin-card-header"><h2>Organizations, subscriptions & credits</h2><span>{orgIds.length}</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Organization</th><th>Role</th><th>Subscription</th><th>Period end</th><th>Credits</th></tr></thead><tbody>{(memberships.data??[]).map(m=>{const s=(subs.data??[]).find(x=>x.organization_id===m.organization_id);const c=(credits.data??[]).find(x=>x.organization_id===m.organization_id);return <tr key={m.organization_id}><td><b>{String((m.app_organizations as unknown as {name?:string})?.name||m.organization_id)}</b><small>{m.organization_id}</small></td><td>{m.role}</td><td>{s?.status||"none"}</td><td>{dt(s?.current_period_end)}</td><td>{Number(c?.balance??0).toLocaleString()}</td></tr>})}</tbody></table></div></section>
 <section className="admin-card"><div className="admin-card-header"><h2>Recent product history</h2><span>AI + usage + purchases</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Time</th><th>Type</th><th>State</th><th>Usage / amount</th><th>Organization</th></tr></thead><tbody>{[
 ...(runs.data??[]).map(x=>({id:`r-${x.id}`,time:x.created_at,type:"agent_run",state:x.state,value:`${Number(x.total_tokens).toLocaleString()} tok · $${Number(x.total_cost).toFixed(4)}`,org:x.organization_id})),
 ...(requests.data??[]).map(x=>({id:`q-${x.id}`,time:x.created_at,type:`AI ${x.task_type}`,state:x.status,value:`${Number(x.input_tokens)+Number(x.output_tokens)} tok · $${Number(x.cost).toFixed(4)}`,org:x.organization_id})),
 ...(transactions.data??[]).map(x=>({id:`p-${x.id}`,time:x.created_at,type:x.kind,state:x.status,value:`${new Intl.NumberFormat("en",{style:"currency",currency:x.currency}).format(Number(x.amount_minor)/100)}${Number(x.credits)>0?` · ${Number(x.credits).toLocaleString()} credits`:""}`,org:x.organization_id}))
 ].sort((a,b)=>new Date(b.time).getTime()-new Date(a.time).getTime()).slice(0,100).map(x=><tr key={x.id}><td>{dt(x.time)}</td><td>{x.type}</td><td>{x.state}</td><td>{x.value}</td><td>{x.org}</td></tr>)}</tbody></table></div></section></div>
}
