import Link from "next/link";
import { notFound } from "next/navigation";
import { getWorkspace } from "@/lib/workspace";
import { addFindingEvidence, appendEvidenceVersion, updateFinding } from "./actions";

function contentText(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))return "";const text=(value as Record<string,unknown>).text;return typeof text==="string"?text:"";}

export default async function FindingPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const ws=await getWorkspace();if(!ws?.organizationId)notFound();
  const {data:finding}=await ws.supabase.schema("security").from("findings").select("id,project_id,engagement_id,title,summary,description,severity,confidence,status,affected_asset,category,impact,recommendation,validated_at,resolved_at,updated_at").eq("id",id).eq("organization_id",ws.organizationId).is("deleted_at",null).maybeSingle();
  if(!finding)notFound();
  const [{data:project},{data:evidence},{data:files}]=await Promise.all([
    ws.supabase.schema("app").from("projects").select("id,name").eq("id",finding.project_id).eq("organization_id",ws.organizationId).maybeSingle(),
    ws.supabase.schema("security").from("finding_evidence").select("id,evidence_type,source_file_id,content_hash,current_version,created_at").eq("finding_id",id).eq("organization_id",ws.organizationId).order("created_at",{ascending:false}),
    ws.supabase.schema("artifacts").from("files").select("id,original_name,status").eq("project_id",finding.project_id).eq("organization_id",ws.organizationId).is("deleted_at",null).order("created_at",{ascending:false}).limit(100),
  ]);
  const evidenceIds=(evidence??[]).map((item)=>item.id);
  const {data:versions}=evidenceIds.length?await ws.supabase.schema("security").from("finding_evidence_versions").select("id,evidence_id,version,content,content_hash,created_at").eq("organization_id",ws.organizationId).in("evidence_id",evidenceIds).order("version",{ascending:false}):{data:[] as Array<{id:string;evidence_id:string;version:number;content:unknown;content_hash:string;created_at:string}>};
  const latestByEvidence=new Map<string,{id:string;evidence_id:string;version:number;content:unknown;content_hash:string;created_at:string}>();
  for(const version of versions??[])if(!latestByEvidence.has(version.evidence_id))latestByEvidence.set(version.evidence_id,version);

  return <div className="app-content">
    <div className="app-heading"><div><div className="section-label">FINDING / {String(finding.severity).toUpperCase()}</div><h1>{finding.title}</h1><p>{project?.name??"Project"} · evidence stays versioned and traceable.</p></div><Link className="button button-small secondary" href={`/app/projects/${finding.project_id}`}>Project →</Link></div>
    <section className="metric-grid"><div className="metric"><span>STATUS</span><strong style={{fontSize:16}}>{String(finding.status).replaceAll("_"," ")}</strong></div><div className="metric"><span>CONFIDENCE</span><strong>{finding.confidence==null?"—":`${finding.confidence}%`}</strong></div><div className="metric"><span>EVIDENCE</span><strong>{evidence?.length??0}</strong></div></section>
    <section className="workspace-grid">
      <article className="workspace-card"><header><h2>Finding review</h2><span>Lifecycle</span></header><form className="auth-form" action={updateFinding} style={{marginTop:16}}><input type="hidden" name="finding_id" value={id}/><input type="hidden" name="organization_id" value={ws.organizationId}/><input type="hidden" name="project_id" value={finding.project_id}/><label>Title<input name="title" required maxLength={240} defaultValue={finding.title}/></label><label>Severity<select name="severity" defaultValue={finding.severity}><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option><option value="informational">Informational</option></select></label><label>Status<select name="status" defaultValue={finding.status}><option value="potential">Potential</option><option value="reviewing">Reviewing</option><option value="validated">Validated</option><option value="reported">Reported</option><option value="remediated">Remediated</option><option value="verified">Verified</option><option value="false_positive">False positive</option><option value="duplicate">Duplicate</option><option value="accepted_risk">Accepted risk</option></select></label><label>Confidence<input name="confidence" type="number" min="0" max="100" step="1" defaultValue={finding.confidence??""}/></label><label>Affected asset<input name="affected_asset" maxLength={1000} defaultValue={finding.affected_asset??""}/></label><label>Category<input name="category" maxLength={200} defaultValue={finding.category??""}/></label><label>Description<textarea name="description" maxLength={12000} defaultValue={finding.description??finding.summary??""}/></label><label>Impact<textarea name="impact" maxLength={6000} defaultValue={finding.impact??""}/></label><label>Recommendation<textarea name="recommendation" maxLength={6000} defaultValue={finding.recommendation??""}/></label><button className="button" type="submit">Save finding</button></form></article>
      <article className="workspace-card"><header><h2>Add evidence</h2><span>Immutable versions</span></header><form className="auth-form" action={addFindingEvidence} style={{marginTop:16}}><input type="hidden" name="finding_id" value={id}/><input type="hidden" name="organization_id" value={ws.organizationId}/><input type="hidden" name="project_id" value={finding.project_id}/><label>Evidence type<select name="evidence_type" defaultValue="text"><option value="text">Text observation</option><option value="log">Log</option><option value="request_response">Request / response</option><option value="source_code_reference">Source-code reference</option><option value="agent_observation">Agent observation</option><option value="file">File reference</option><option value="screenshot">Screenshot note</option><option value="image">Image note</option></select></label><label>Source file<select name="source_file_id" defaultValue=""><option value="">No source file</option>{(files??[]).map((file)=><option value={file.id} key={file.id}>{file.original_name} · {file.status}</option>)}</select></label><label>Evidence content<textarea name="content" required maxLength={20000} placeholder="Observed behavior, log excerpt, request/response summary or source reference…"/></label><button className="button" type="submit">Add evidence</button></form></article>
    </section>
    <section className="workspace-card"><header><h2>Evidence trail</h2><span>{evidence?.length??0} artifacts</span></header>{evidence?.length?evidence.map((item)=>{const latest=latestByEvidence.get(item.id);return <div key={item.id} style={{borderTop:"1px solid #20262c",padding:"18px 0"}}><div className="project-row" style={{borderTop:0}}><div><b>{item.evidence_type.replaceAll("_"," ")}</b><small>version {item.current_version} · SHA-256 {item.content_hash?.slice(0,16)??"—"}… · {new Date(item.created_at).toLocaleString("en-GB")}</small></div><span>{item.source_file_id?"FILE-LINKED":"MANUAL"}</span></div>{latest?<p style={{whiteSpace:"pre-wrap",color:"#aab1b9",padding:"0 12px"}}>{contentText(latest.content)}</p>:null}<form className="workspace-form" action={appendEvidenceVersion}><input type="hidden" name="finding_id" value={id}/><input type="hidden" name="organization_id" value={ws.organizationId}/><input type="hidden" name="project_id" value={finding.project_id}/><input type="hidden" name="evidence_id" value={item.id}/><input name="content" required maxLength={20000} placeholder="Create a new version — the previous one remains unchanged"/><button className="button button-small secondary" type="submit">New version</button></form></div>}):<div className="empty-state"><div><b>No evidence yet.</b><p>Add source-backed evidence before moving a finding to validated.</p></div></div>}</section>
  </div>;
}
