-- Tenant identity is enforced at the relational layer, not only through RLS.
alter table app.projects add constraint projects_id_org_unique unique(id,organization_id);
alter table app.conversations add constraint conversations_id_org_unique unique(id,organization_id);
alter table security.engagements add constraint engagements_id_org_unique unique(id,organization_id);
alter table security.findings add constraint findings_id_org_unique unique(id,organization_id);
alter table artifacts.files add constraint files_id_org_unique unique(id,organization_id);
alter table ai.agent_runs add constraint agent_runs_id_org_unique unique(id,organization_id);
alter table ai.tool_runs add constraint tool_runs_id_org_unique unique(id,organization_id);
alter table security.finding_evidence add constraint finding_evidence_id_org_unique unique(id,organization_id);
alter table reports.report_templates add constraint report_templates_id_org_unique unique(id,organization_id);
alter table reports.reports add constraint reports_id_org_unique unique(id,organization_id);
alter table reports.report_versions add constraint report_versions_id_org_unique unique(id,organization_id);
alter table app.api_clients add constraint api_clients_id_org_unique unique(id,organization_id);

alter table app.project_members add constraint project_members_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete cascade;
alter table app.project_notes add constraint project_notes_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete cascade;
alter table app.conversations add constraint conversations_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete set null (project_id);
alter table app.messages add constraint messages_conversation_org_fk foreign key(conversation_id,organization_id) references app.conversations(id,organization_id) on delete cascade;
alter table security.engagements add constraint engagements_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete cascade;
alter table security.authorization_records add constraint authorization_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete cascade;
alter table security.authorization_records add constraint authorization_engagement_org_fk foreign key(engagement_id,organization_id) references security.engagements(id,organization_id) on delete cascade;
alter table security.engagement_scope add constraint scope_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete cascade;
alter table security.engagement_scope add constraint scope_engagement_org_fk foreign key(engagement_id,organization_id) references security.engagements(id,organization_id) on delete cascade;
alter table security.findings add constraint findings_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete cascade;
alter table security.findings add constraint findings_engagement_org_fk foreign key(engagement_id,organization_id) references security.engagements(id,organization_id) on delete set null (engagement_id);
alter table security.findings add constraint findings_agent_org_fk foreign key(source_agent_run_id,organization_id) references ai.agent_runs(id,organization_id) on delete set null (source_agent_run_id);
alter table artifacts.files add constraint files_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete cascade;
alter table artifacts.file_versions add constraint file_versions_file_org_fk foreign key(file_id,organization_id) references artifacts.files(id,organization_id) on delete cascade;
alter table artifacts.file_chunks add constraint file_chunks_file_org_fk foreign key(file_id,organization_id) references artifacts.files(id,organization_id) on delete cascade;
alter table artifacts.file_chunks add constraint file_chunks_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete cascade;
alter table ai.agent_runs add constraint agent_runs_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete cascade;
alter table ai.agent_runs add constraint agent_runs_engagement_org_fk foreign key(engagement_id,organization_id) references security.engagements(id,organization_id) on delete set null (engagement_id);
alter table ai.agent_run_steps add constraint agent_steps_run_org_fk foreign key(agent_run_id,organization_id) references ai.agent_runs(id,organization_id) on delete cascade;
alter table ai.agent_checkpoints add constraint agent_checkpoints_run_org_fk foreign key(agent_run_id,organization_id) references ai.agent_runs(id,organization_id) on delete cascade;
alter table ai.tool_runs add constraint tool_runs_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete cascade;
alter table ai.tool_runs add constraint tool_runs_engagement_org_fk foreign key(engagement_id,organization_id) references security.engagements(id,organization_id) on delete set null (engagement_id);
alter table ai.tool_runs add constraint tool_runs_agent_org_fk foreign key(agent_run_id,organization_id) references ai.agent_runs(id,organization_id) on delete cascade;
alter table ai.tool_runs add constraint tool_runs_artifact_org_fk foreign key(raw_artifact_file_id,organization_id) references artifacts.files(id,organization_id) on delete set null (raw_artifact_file_id);
alter table ai.generation_requests add constraint generation_conversation_org_fk foreign key(conversation_id,organization_id) references app.conversations(id,organization_id) on delete set null (conversation_id);
alter table ai.generation_requests add constraint generation_agent_org_fk foreign key(agent_run_id,organization_id) references ai.agent_runs(id,organization_id) on delete set null (agent_run_id);
alter table ai.memory_items add constraint memory_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete cascade;
alter table security.finding_evidence add constraint evidence_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete cascade;
alter table security.finding_evidence add constraint evidence_finding_org_fk foreign key(finding_id,organization_id) references security.findings(id,organization_id) on delete cascade;
alter table security.finding_evidence add constraint evidence_tool_org_fk foreign key(source_tool_run_id,organization_id) references ai.tool_runs(id,organization_id) on delete set null (source_tool_run_id);
alter table security.finding_evidence add constraint evidence_agent_org_fk foreign key(source_agent_run_id,organization_id) references ai.agent_runs(id,organization_id) on delete set null (source_agent_run_id);
alter table security.finding_evidence add constraint evidence_file_org_fk foreign key(source_file_id,organization_id) references artifacts.files(id,organization_id) on delete set null (source_file_id);
alter table security.finding_evidence_versions add constraint evidence_versions_evidence_org_fk foreign key(evidence_id,organization_id) references security.finding_evidence(id,organization_id) on delete cascade;
alter table reports.reports add constraint reports_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete cascade;
alter table reports.reports add constraint reports_engagement_org_fk foreign key(engagement_id,organization_id) references security.engagements(id,organization_id) on delete set null (engagement_id);
alter table reports.reports add constraint reports_template_org_fk foreign key(template_id,organization_id) references reports.report_templates(id,organization_id) on delete set null (template_id);
alter table reports.report_versions add constraint report_versions_report_org_fk foreign key(report_id,organization_id) references reports.reports(id,organization_id) on delete cascade;
alter table reports.report_sections add constraint report_sections_report_org_fk foreign key(report_id,organization_id) references reports.reports(id,organization_id) on delete cascade;
alter table reports.report_exports add constraint report_exports_report_org_fk foreign key(report_id,organization_id) references reports.reports(id,organization_id) on delete cascade;
alter table reports.report_exports add constraint report_exports_version_org_fk foreign key(report_version_id,organization_id) references reports.report_versions(id,organization_id) on delete set null (report_version_id);
alter table reports.report_exports add constraint report_exports_file_org_fk foreign key(storage_file_id,organization_id) references artifacts.files(id,organization_id) on delete set null (storage_file_id);
alter table usage.usage_events add constraint usage_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete set null (project_id);
alter table usage.usage_events add constraint usage_agent_org_fk foreign key(agent_run_id,organization_id) references ai.agent_runs(id,organization_id) on delete set null (agent_run_id);
alter table security.approval_requests add constraint approval_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete cascade;
alter table security.approval_requests add constraint approval_engagement_org_fk foreign key(engagement_id,organization_id) references security.engagements(id,organization_id) on delete cascade;
alter table security.approval_requests add constraint approval_agent_org_fk foreign key(agent_run_id,organization_id) references ai.agent_runs(id,organization_id) on delete cascade;
alter table security.approval_requests add constraint approval_tool_org_fk foreign key(tool_run_id,organization_id) references ai.tool_runs(id,organization_id) on delete cascade;
alter table operations.sandbox_jobs add constraint sandbox_project_org_fk foreign key(project_id,organization_id) references app.projects(id,organization_id) on delete cascade;
alter table operations.sandbox_jobs add constraint sandbox_engagement_org_fk foreign key(engagement_id,organization_id) references security.engagements(id,organization_id) on delete cascade;
alter table operations.sandbox_jobs add constraint sandbox_tool_org_fk foreign key(tool_run_id,organization_id) references ai.tool_runs(id,organization_id) on delete cascade;
alter table operations.network_logs add constraint network_tool_org_fk foreign key(tool_run_id,organization_id) references ai.tool_runs(id,organization_id) on delete cascade;
alter table app.api_keys add constraint api_keys_client_org_fk foreign key(client_id,organization_id) references app.api_clients(id,organization_id) on delete cascade;
