create index if not exists agent_evaluations_baseline_profile_version_idx on ai.agent_evaluations(baseline_profile_version_id) where baseline_profile_version_id is not null;
create index if not exists agent_model_preferences_model_alias_idx on ai.agent_model_preferences(model_alias);
create index if not exists agent_profile_versions_created_by_idx on ai.agent_profile_versions(created_by) where created_by is not null;
create index if not exists agent_profiles_created_by_idx on ai.agent_profiles(created_by) where created_by is not null;
create index if not exists agent_runs_profile_version_idx on ai.agent_runs(agent_profile_version_id) where agent_profile_version_id is not null;
create index if not exists agent_runs_requested_model_alias_idx on ai.agent_runs(requested_model_alias) where requested_model_alias is not null;
create index if not exists agent_tool_assignments_tool_idx on ai.agent_tool_assignments(tool_definition_id);
create index if not exists generation_requests_profile_version_idx on ai.generation_requests(agent_profile_version_id) where agent_profile_version_id is not null;
create index if not exists generation_requests_requested_model_alias_idx on ai.generation_requests(requested_model_alias) where requested_model_alias is not null;
create index if not exists learning_candidates_created_by_idx on ai.learning_candidates(created_by) where created_by is not null;
create index if not exists learning_candidates_org_idx on ai.learning_candidates(organization_id) where organization_id is not null;
create index if not exists learning_candidates_agent_run_idx on ai.learning_candidates(source_agent_run_id) where source_agent_run_id is not null;
create index if not exists learning_candidates_generation_request_idx on ai.learning_candidates(source_generation_request_id) where source_generation_request_id is not null;
create index if not exists model_entitlements_alias_idx on ai.model_entitlements(model_alias);
create index if not exists rollouts_created_by_idx on ai.rollouts(created_by) where created_by is not null;
create index if not exists conversations_agent_profile_idx on app.conversations(agent_profile_id) where agent_profile_id is not null;
create index if not exists conversations_agent_profile_version_idx on app.conversations(agent_profile_version_id) where agent_profile_version_id is not null;
create index if not exists conversations_selected_model_alias_idx on app.conversations(selected_model_alias) where selected_model_alias is not null;
create index if not exists user_model_preferences_model_alias_idx on app.user_model_preferences(model_alias) where model_alias is not null;
create index if not exists policy_assignments_assigned_by_idx on policies.policy_assignments(assigned_by) where assigned_by is not null;
create index if not exists policy_change_logs_actor_idx on policies.policy_change_logs(actor_user_id) where actor_user_id is not null;
create index if not exists policy_change_logs_version_idx on policies.policy_change_logs(policy_version_id) where policy_version_id is not null;
create index if not exists policy_decisions_project_idx on policies.policy_decisions(project_id) where project_id is not null;
create index if not exists policy_decisions_user_idx on policies.policy_decisions(user_id) where user_id is not null;
create index if not exists policy_exceptions_created_by_idx on policies.policy_exceptions(created_by) where created_by is not null;
create index if not exists policy_exceptions_rule_idx on policies.policy_exceptions(rule_id);
create index if not exists policy_sets_created_by_idx on policies.policy_sets(created_by) where created_by is not null;
create index if not exists policy_versions_created_by_idx on policies.policy_versions(created_by) where created_by is not null;