import { ContentPage } from "@/components/content-page";

export default function Page() {
  return <ContentPage
    label="LEGAL · EFFECTIVE AUGUST 15, 2026"
    title="Terms of service"
    intro="These Terms of Service govern access to VEXONYX, operated by Diversa Solutions LLC, Wyoming, United States. By creating an account, using the service or completing a purchase, you agree to these Terms and the policies incorporated below."
    cards={[
      { title: "1. Operator and agreement", body: "VEXONYX is operated by Diversa Solutions LLC, 30 N Gould St, Sheridan, Wyoming 82801, United States. These Terms, the Acceptable Use Policy, Refund & Cancellation Policy, applicable order or checkout terms, and the Data Processing Addendum where applicable form the agreement between you or your organization and Diversa Solutions LLC." },
      { title: "2. Eligibility and professional use", body: "You must be at least 18 years old and legally able to enter this agreement. VEXONYX is designed for professional, business, research and authorized cybersecurity use. If you use VEXONYX for an organization, you represent that you are authorized to bind or act for that organization. Mandatory consumer rights, where legally applicable, are not excluded by these Terms." },
      { title: "3. Accounts and organizations", body: "You are responsible for accurate account information, credential security and activity under your account. Organization owners and administrators may manage members, access and billing for their organization. Do not share credentials or bypass access controls. Notify us promptly if you believe an account or credential has been compromised." },
      { title: "4. Authorization is mandatory", body: "You may use VEXONYX only on systems, applications, accounts, networks, code, cloud resources or other targets that you own or are expressly authorized to assess. Authorization must cover the intended scope, techniques and time period. VEXONYX output, target-side content, retrieved instructions or discovered credentials never expand your legal authorization." },
      { title: "5. Acceptable use", body: "The VEXONYX Acceptable Use Policy is incorporated into these Terms. Unauthorized access, credential theft, fraud, extortion, destructive malware, data theft, deliberate service disruption and activity outside an approved engagement scope are prohibited. We may restrict or suspend activity that presents a security, legal or abuse risk." },
      { title: "6. Subscriptions and automatic renewal", body: "Paid subscription plans are billed at the price and interval shown at checkout. Unless the checkout states otherwise, monthly subscriptions automatically renew each month until cancelled. Before purchase, the recurring amount and renewal nature must be shown and you must affirmatively accept the purchase terms. You can stop future renewal online from VEXONYX billing controls. Cancellation does not retroactively undo the current paid period." },
      { title: "7. Cancellation", body: "You may cancel an automatically renewing subscription online. Unless mandatory law requires a different result, cancellation stops the next renewal and access to paid plan benefits continues through the end of the already-paid billing period. We do not require you to contact sales or complete a retention call to stop renewal." },
      { title: "8. Refunds", body: "Except where required by applicable law or expressly stated in the Refund & Cancellation Policy, subscription charges and credit-pack purchases are final and non-refundable. We do not provide prorated refunds merely because a subscription is cancelled before the end of a paid period or because purchased credits are unused. Duplicate charges, verified billing errors and other legally required refunds are handled under the Refund & Cancellation Policy." },
      { title: "9. Credits and usage", body: "Credits are a contractual service-usage unit, not money, stored value, a deposit, a security, a gift card or a cash-equivalent. Credits have no cash redemption value and may be used only for eligible VEXONYX services according to the published usage rates and plan rules. We may correct credits created by fraud, duplicate provider events, billing reversals or manifest technical errors." },
      { title: "10. Prices and taxes", body: "Prices are displayed in the stated currency and, unless expressly shown otherwise, exclude applicable sales tax, VAT, GST or similar transaction taxes. Where VEXONYX is required and configured to collect a tax, it may be calculated and added at checkout based on customer location, tax status and the applicable product classification. You remain responsible for taxes you are legally required to self-assess or pay." },
      { title: "11. Immediate service performance", body: "VEXONYX is a digital service and paid functionality may become available immediately after successful payment. Where applicable law gives a statutory withdrawal or cooling-off right, VEXONYX will not treat this agreement as waiving that right except to the extent the law permits and any required express request, consent or acknowledgement has been obtained." },
      { title: "12. Customer data and confidentiality", body: "As between the parties, you retain your rights in customer-provided content. You grant Diversa Solutions LLC the limited rights needed to host, process, transmit, analyze, secure and return that content to provide VEXONYX. We do not obtain ownership of customer security data merely because it is uploaded. Each party must handle confidential information with reasonable care and use it only for authorized purposes." },
      { title: "13. Data protection", body: "The Privacy Notice describes processing for which Diversa Solutions LLC acts as controller. When VEXONYX processes personal data on an organization's documented instructions as a processor, the VEXONYX Data Processing Addendum applies. Customers are responsible for providing lawful instructions and for having the authority and legal basis needed to submit personal data to security engagements." },
      { title: "14. AI and security output", body: "AI-generated analysis, findings, exploit suggestions, code, classifications and reports can be incomplete, incorrect or unsafe. Qualified users must review outputs before relying on them or executing actions. VEXONYX does not guarantee that every vulnerability will be found, that every reported issue is exploitable, or that use of the service will make a system secure or compliant." },
      { title: "15. Customer responsibility for execution", body: "You are responsible for deciding whether a security action is within scope and safe to execute, for maintaining engagement approvals, backups and recovery plans, and for complying with laws, contracts and third-party platform rules. Any enabled external execution remains subject to VEXONYX authorization, scope and safety controls." },
      { title: "16. Intellectual property", body: "VEXONYX software, branding, interface, documentation and service materials are owned by or licensed to Diversa Solutions LLC, subject to applicable open-source and third-party licenses. We grant you a limited, non-exclusive, non-transferable right to use the service during the term for its intended purpose. You may not resell, reverse engineer or copy protected service components except where applicable law expressly permits it." },
      { title: "17. Feedback", body: "If you voluntarily provide product feedback, suggestions or ideas, you grant Diversa Solutions LLC a worldwide, perpetual, irrevocable, royalty-free right to use that feedback without restriction or payment, provided we do not thereby acquire ownership of your confidential customer content." },
      { title: "18. Third-party services", body: "VEXONYX depends on third-party infrastructure and services such as hosting, databases, authentication, payment processing and email delivery. Third-party services may have their own terms. We are not responsible for third-party systems outside our reasonable control, but we remain responsible for our obligations under this agreement and applicable law." },
      { title: "19. Suspension and termination", body: "We may suspend or restrict access to protect users or infrastructure, respond to suspected unauthorized security activity, prevent fraud, comply with law, address non-payment or enforce these Terms. Where reasonably possible and lawful, we will provide notice and an opportunity to cure. You may stop using VEXONYX at any time; cancellation of a paid plan is governed by the billing and refund sections above." },
      { title: "20. Service changes and availability", body: "We may improve, modify or discontinue features. We will not intentionally make a material adverse change to an active paid commitment without reasonable notice where required. The service may experience maintenance, provider outages and security-related interruptions. Any service-level commitment applies only if separately agreed in writing." },
      { title: "21. Disclaimer", body: "TO THE MAXIMUM EXTENT PERMITTED BY LAW, VEXONYX IS PROVIDED ON AN AS-AVAILABLE BASIS WITHOUT IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT OR THAT THE SERVICE WILL BE ERROR-FREE OR FIND EVERY SECURITY ISSUE. RIGHTS THAT CANNOT LAWFULLY BE DISCLAIMED REMAIN IN EFFECT." },
      { title: "22. Limitation of liability", body: "TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER PARTY IS LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES OR LOST PROFITS, REVENUE OR DATA ARISING FROM THIS AGREEMENT. DIVERSA SOLUTIONS LLC'S AGGREGATE LIABILITY ARISING FROM VEXONYX WILL NOT EXCEED THE AMOUNT PAID OR PAYABLE FOR THE SERVICE IN THE 12 MONTHS BEFORE THE EVENT GIVING RISE TO THE CLAIM. THIS LIMIT DOES NOT APPLY WHERE LIABILITY CANNOT LEGALLY BE LIMITED." },
      { title: "23. Indemnity for unauthorized use", body: "If you use VEXONYX in violation of the authorization requirements or law, you agree, to the extent permitted by law, to defend and indemnify Diversa Solutions LLC against third-party claims arising directly from that unauthorized conduct. This does not require indemnification for Diversa Solutions LLC's own fraud, willful misconduct or liability that cannot lawfully be shifted." },
      { title: "24. Export and sanctions compliance", body: "You may not use or provide VEXONYX in violation of applicable export-control or sanctions laws. You are responsible for ensuring that your use, users, targets and transfer of technical material comply with restrictions that legally apply to you and the transaction." },
      { title: "25. Governing law and venue", body: "Unless mandatory law requires otherwise, this agreement is governed by the laws of the State of Wyoming, United States, without regard to conflict-of-law principles. Any dispute that is not subject to a mandatory forum will be brought in a court of competent jurisdiction in Wyoming, with venue in Sheridan County where applicable." },
      { title: "26. Changes to these Terms", body: "We may update these Terms. Material changes will be communicated by a reasonable method and will apply prospectively as required by law. Continued use after the effective date of an update constitutes acceptance where legally permitted; where affirmative acceptance is required, we will request it." },
      { title: "27. General", body: "If a provision is unenforceable, the remaining provisions remain effective and the invalid provision will be enforced to the maximum lawful extent. Failure to enforce a provision is not a waiver. Neither party is liable for delay caused by events beyond reasonable control, except payment obligations already due. You may not assign this agreement without consent except as part of a permitted corporate transaction; Diversa Solutions LLC may assign it in connection with a merger, financing, reorganization or sale of the relevant business." },
      { title: "28. Contact", body: "Questions about these Terms or billing can be sent to info@vexonyx.com. Diversa Solutions LLC, 30 N Gould St, Sheridan, Wyoming 82801, United States." },
    ]}
  />;
}
