import { requireSuperadmin } from "@/lib/admin/guard";
import { adjustCredits, saveCreditProduct } from "../commerce-actions";

function money(minor:unknown,currency:unknown){return new Intl.NumberFormat("en",{style:"currency",currency:String(currency||"USD")}).format(Number(minor||0)/100)}
export default async function AdminCreditsPage(){
 const {admin}=await requireSuperadmin();
 const [products,accounts,ledger,orgs]=await Promise.all([
  admin.schema("billing").from("credit_products").select("id,code,name,description,credits,currency,unit_amount_minor,provider_price_id,active,updated_at").order("display_order"),
  admin.schema("billing").from("credit_accounts").select("organization_id,balance,lifetime_purchased,lifetime_granted,lifetime_consumed,updated_at").order("balance",{ascending:false}).limit(500),
  admin.schema("billing").from("credit_ledger").select("id,organization_id,user_id,entry_type,amount,balance_after,external_reference,metadata,created_at").order("created_at",{ascending:false}).limit(100),
  admin.schema("app").from("organizations").select("id,name,status").order("name").limit(1000)
 ]);
 const orgName=new Map((orgs.data??[]).map(o=>[o.id,o.name]));
 return <div className="admin-page"><div className="admin-heading"><div className="admin-heading-copy"><div className="admin-eyebrow">VEXONYX / COMMERCE</div><h1>Credits</h1><p>Credits are an append-only ledger with an atomic balance. Purchases, grants, usage, refunds and manual adjustments remain traceable.</p></div></div>
 <section className="admin-grid equal"><article className="admin-card"><div className="admin-card-header"><h2>Create credit pack</h2><span>Provider-backed</span></div><form className="admin-card-body admin-form" action={saveCreditProduct}><input className="admin-input" name="code" placeholder="credits_10k" required/><input className="admin-input" name="name" placeholder="10,000 credits" required/><textarea className="admin-input" name="description" placeholder="Optional description"/><input className="admin-input" name="credits" type="number" min="1" placeholder="10000" required/><input className="admin-input" name="unit_amount_minor" type="number" min="1" placeholder="2500" required/><input className="admin-input" name="currency" defaultValue="USD" maxLength={3}/><input className="admin-input" name="provider_price_id" placeholder="price_..."/><label><input type="checkbox" name="active" value="true"/> Active for customer checkout</label><button className="admin-button primary" type="submit">Create credit pack</button></form></article>
 <article className="admin-card"><div className="admin-card-header"><h2>Manual adjustment</h2><span>Audited</span></div><form className="admin-card-body admin-form" action={adjustCredits}><select className="admin-input" name="organization_id" required><option value="">Choose organization</option>{(orgs.data??[]).map(o=><option key={o.id} value={o.id}>{o.name} · {o.status}</option>)}</select><input className="admin-input" name="amount" type="number" placeholder="5000 or -5000" required/><textarea className="admin-input" name="reason" placeholder="Reason for adjustment" required/><button className="admin-button" type="submit">Apply adjustment</button></form></article></section>
 <section className="admin-card"><div className="admin-card-header"><h2>Credit products</h2><span>{products.data?.length??0}</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Product</th><th>Credits</th><th>Price</th><th>Checkout</th><th>Provider price</th></tr></thead><tbody>{(products.data??[]).map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.code}</small></td><td>{Number(p.credits).toLocaleString()}</td><td>{money(p.unit_amount_minor,p.currency)}</td><td>{p.active?"active":"inactive"}</td><td><small>{p.provider_price_id||"—"}</small></td></tr>)}</tbody></table></div></section>
 <section className="admin-card"><div className="admin-card-header"><h2>Organization balances</h2><span>{accounts.data?.length??0}</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Organization</th><th>Balance</th><th>Purchased</th><th>Granted</th><th>Consumed</th></tr></thead><tbody>{(accounts.data??[]).map(a=><tr key={a.organization_id}><td><b>{orgName.get(a.organization_id)||a.organization_id}</b><small>{a.organization_id}</small></td><td>{Number(a.balance).toLocaleString()}</td><td>{Number(a.lifetime_purchased).toLocaleString()}</td><td>{Number(a.lifetime_granted).toLocaleString()}</td><td>{Number(a.lifetime_consumed).toLocaleString()}</td></tr>)}</tbody></table></div></section>
 <section className="admin-card"><div className="admin-card-header"><h2>Ledger</h2><span>Latest 100</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Organization</th><th>Entry</th><th>Amount</th><th>Balance after</th><th>Reference</th><th>Time</th></tr></thead><tbody>{(ledger.data??[]).map(l=><tr key={l.id}><td>{orgName.get(l.organization_id)||l.organization_id}</td><td>{l.entry_type}</td><td>{Number(l.amount).toLocaleString()}</td><td>{Number(l.balance_after).toLocaleString()}</td><td><small>{l.external_reference||"—"}</small></td><td>{new Date(l.created_at).toLocaleString("en-GB")}</td></tr>)}</tbody></table></div></section></div>
}
